services:
  carousel:
    image: ghcr.io/morgankryze/carousel:stable
    container_name: carousel
    restart: unless-stopped
    user: root
    privileged: true
    devices:
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
    volumes:
      - ../configs:/app/configs
      - ../logs:/app/logs
      - ../data:/app/data
    network_mode: host
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - watchtower
  
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Paris
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_UPDATE_ON_START: true
      # SPRING For 4 AM daily update checks
      WATCHTOWER_SCHEDULE: 0 0 4 * * *